using System;
using System.IO;
using Xunit;
using Serilog.Events;
using Serilog.Tests.Support;
using Serilog.Context;

namespace Serilog.Tests.AppSettings.Tests
{
    public class AppSettingsTests
    {
        static string GetConfigPath()
        {
            var basePath = AppDomain.CurrentDomain.BaseDirectory;
            return Path.GetFullPath(Path.Combine(basePath, "tests.config"));
        }

        [Fact]
        public void TheTestConfigFileExists()
        {
            var config= GetConfigPath();
            Assert.True(File.Exists(config), "Can't find the test configuration file");
        }

        [Fact]
        public void EnvironmentVariableExpansionIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath()) 
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Information("Has a Path property with value expanded from the environment variable");

            Assert.NotNull(evt);
            Assert.NotEmpty((string)evt.Properties["Path"].LiteralValue());
            Assert.NotEqual("%PATH%", evt.Properties["Path"].LiteralValue());
        }

        [Fact]
        public void CanUseCustomPrefixToConfigureSettings()
        {
            const string prefix1 = "custom1";
            const string prefix2 = "custom2";

            var log1 = new LoggerConfiguration()
                .WriteTo.Observers(o => { })
                .ReadFrom.AppSettings(prefix1, filePath: GetConfigPath())
                .CreateLogger();

            var log2 = new LoggerConfiguration()
                .WriteTo.Observers(o => { })
                .ReadFrom.AppSettings(prefix2, filePath: GetConfigPath())
                .CreateLogger();

            Assert.False(log1.IsEnabled(LogEventLevel.Information));
            Assert.True(log1.IsEnabled(LogEventLevel.Warning));

            Assert.False(log2.IsEnabled(LogEventLevel.Warning));
            Assert.True(log2.IsEnabled(LogEventLevel.Error));
        }

        [Fact]
        public void CustomPrefixCannotContainColon()
        {
            Assert.Throws<ArgumentException>(() =>
                new LoggerConfiguration().ReadFrom.AppSettings("custom1:custom2", filePath: GetConfigPath()));
        }

        [Fact]
        public void CustomPrefixCannotBeSerilog()
        {
            Assert.Throws<ArgumentException>(() =>
                new LoggerConfiguration().ReadFrom.AppSettings("serilog", filePath: GetConfigPath()));
        }

        [Fact]
        public void ThreadIdEnricherIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath())
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Information("Has a ThreadId property with value generated by ThreadIdEnricher");

            Assert.NotNull(evt);
            Assert.NotNull(evt.Properties["ThreadId"]);
            Assert.NotNull(evt.Properties["ThreadId"].LiteralValue() as int?);
        }

        [Fact]
        public void MachineNameEnricherIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath())
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Information("Has a MachineName property with value generated by MachineNameEnricher");

            Assert.NotNull(evt);
            Assert.NotNull(evt.Properties["MachineName"]);
            Assert.NotEmpty((string)evt.Properties["MachineName"].LiteralValue());
        }

        [Fact]
        public void EnrivonmentUserNameEnricherIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath())
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Information("Has a EnrivonmentUserName property with value generated by EnrivonmentUserNameEnricher");

            Assert.NotNull(evt);
            Assert.NotNull(evt.Properties["EnvironmentUserName"]);
            Assert.NotEmpty((string)evt.Properties["EnvironmentUserName"].LiteralValue());
        }

        [Fact]
        public void ProcessIdEnricherIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath())
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Information("Has a ProcessId property with value generated by ProcessIdEnricher");

            Assert.NotNull(evt);
            Assert.NotNull(evt.Properties["ProcessId"]);
            Assert.NotNull(evt.Properties["ProcessId"].LiteralValue() as int?);
        }

        [Fact]
        public void LogContextEnricherIsApplied()
        {
            LogEvent evt = null;
            var log = new LoggerConfiguration()
                .ReadFrom.AppSettings(filePath: GetConfigPath())
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            using (LogContext.PushProperty("A", 1))
            {
                log.Information("Has a LogContext property with value generated by LogContextEnricher");
            }

            Assert.NotNull(evt);
            Assert.NotNull(evt.Properties["A"]);
            Assert.NotNull(evt.Properties["A"].LiteralValue() as int?);
            Assert.Equal(1, (int)evt.Properties["A"].LiteralValue());
        }
    }
}
